id: P001726
initial_creation_type: ocr
source_metadata:
  id: bdr:W22017
  title: སྨུག་གུ་དྲེལ་རྫོང་།
  author: ''
  volumes:
    1cff9f31cfc442a8b7f0e9a04b5ee173:
      image_group_id: I1KG17635
      title: ''
      volume_number: 1
      total_pages: 684
