id: IAA8DBCB5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:47:34+00:00'
last_modified: '2022-06-07T14:13:05.866055+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22017
  title: སྨུག་གུ་དྲེལ་རྫོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    381B:
      image_group_id: I1KG17635
      title: ''
      total_pages: 684
      order: 1
      base_file: 381B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
